-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local augroup = vim.api.nvim_create_augroup("UserAutoCmds", { clear = true })

-- Auto save when switching buffers (skip on exit)
-- vim.api.nvim_create_autocmd("BufLeave", {
-- 	group = augroup,
-- 	pattern = "*",
-- 	nested = true,
-- 	callback = function()
-- 		if vim.v.exiting ~= 0 then
-- 			return
-- 		end
-- 		if vim.bo.modified and vim.bo.buftype == "" and vim.fn.expand("%") ~= "" then
-- 			vim.cmd("silent! update")
-- 		end
-- 	end,
-- 	desc = "Auto save on buffer leave (not on exit)",
-- })
