return {
	-- "zbirenbaum/copilot.lua",
	-- cmd = "Copilot",
	-- build = ":Copilot auth",
	-- event = "BufReadPost",
	-- opts = {
	-- 	suggestion = {
	-- 		enabled = true,
	-- 		auto_trigger = true,
	-- 		hide_during_completion = true,
	-- 		debounce = 75,
	-- 		keymap = {
	-- 			accept = "<CR>",
	-- 			accept_word = "<M-Right>",
	-- 			accept_line = "<M-l>",
	-- 			next = "<M-]>",
	-- 			prev = "<M-[>",
	-- 			dismiss = "<C-]>",
	-- 		},
	-- 	},
	-- 	panel = { enabled = false },
	-- 	filetypes = {
	-- 		markdown = true,
	-- 		help = true,
	-- 	},
	-- },
}
